name: Run every 5 minutes

on:
    schedule:
        - cron: '*/5 * * * *'

jobs:
    cron:
      name: Run every 5 minutes
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - name: Hello World
          run: echo 'Hello World!'
