name: Secrets workflow
permissions:
  contents: read

on:
  pull_request:
    branches: ["main"]

env:
  API_CSPROJ_PATH: "./src/ActionsDotNet.Api/ActionsDotNet.Api.csproj"

jobs:
  build:
    name: Secrets demo
    runs-on: ubuntu-latest
    env:
      SECRET_NUMBER: "999"

    steps:
      - name: echo env var
        run: echo "$API_CSPROJ_PATH"
      - name: echo secret number
        run: echo $SECRET_NUMBER

  another_job:
    name: Another job
    runs-on: ubuntu-latest
    env:
      SECRET_NUMBER: "420"

    steps:
      - name: echo secret number
        run: echo $SECRET_NUMBER
