name: Secrets workflow

on:
  pull_request:
    branches: ["main"]

env:
  API_CSPROJ_PATH: "./src/ActionsDotNet.Api/ActionsDotNet.Api.csproj"

jobs:
  build:
    name: Secrets demo
    runs-on: ubuntu-latest

    steps:
      - name: echo env var
        run: echo "$API_CSPROJ_PATH"
